sudo: required

services:
  - docker

before_install:
  - docker build -t plasma018/vip3-lock .

script:
  - ID=$(docker run -e REGION=ap-northeast-1 -e ENDPOINT=https://dynamodb.ap-northeast-1.amazonaws.com -e NODE_ENV=production -e ACCESS_KEY_ID=$ACCESS_KEY_ID -e ACCESS_KEY=$ACCESS_KEY -d plasma018/vip3-lock npm start)
  - docker exec $ID npm install mocha -g
  - docker exec $ID npm install supertest
  - docker exec $ID npm test

