AWSTemplateFormatVersion: '2010-09-09'
Description: vip3 lock ECS configure
Parameters:
  AppContainerPort:
    Type: Number
    Description: Container port
  StackName:
    Type: String
    Description: vip3 lock StackName

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${AWS::StackName}-Cluster

  Taskdefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - "FARGATE"
      NetworkMode: awsvpc
      Cpu: 256
      Memory: 512
      ExecutionRoleArn:
        Fn::ImportValue:
          !Sub "${StackName}-iam:ECSTaskExecutionRole"
      TaskRoleArn:
        Fn::ImportValue:
          !Sub "${StackName}-iam:Vip3DynamodbRole"
      ContainerDefinitions:
        - Name: vip3-lock-cloudformation
          Image: plasma018/vip3-lock
          Cpu: 256
          Memory: 512
          Essential: true
          PortMappings:
            - ContainerPort: !Ref AppContainerPort
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: 'vip3-lock-log'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: web-service

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      ServiceName: !Sub ${AWS::StackName}-Service
      TaskDefinition: !Ref Taskdefinition
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: 
          - Fn::ImportValue:
              !Sub "${StackName}-vpc-PublicSubnet1"
          SecurityGroups:
          - Fn::ImportValue:
              !Sub "${StackName}-vpc-SecurityGroup"


      
      
      
    